name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Amiya-Bot
      uses: actions/checkout@v3
      with:
        repository: 'AmiyaBot/Amiya-Bot'
        path: Amiya-Bot

    - name: Checkout Amiya-Bot-core
      uses: actions/checkout@v3
      with:
        repository: 'AmiyaBot/Amiya-Bot-core'
        path: Amiya-Bot-core

    - name: Checkout Amiya-Bot-docker
      uses: actions/checkout@v3
      with:
        path: Amiya-Bot-docker

    - name: List files and directories
      run: |
        pwd
        ls -lah 
        tree

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Amiya-Bot-docker/Dockerfile --tag hsyhhssyy/amiyabot:$(date +%s)
